#!/usr/bin/env python3
"""Read content.json and emit generated assets for the Vite impact site.

Python crafts: sections HTML, teal/coral palette CSS (light+dark),
and a procedural book/leaf motif SVG — so the build pipeline shapes art direction.
"""

from __future__ import annotations

import html
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONTENT_PATH = ROOT / "content.json"
OUT_DIR = ROOT / "src" / "generated"
PUBLIC_DIR = ROOT / "public"
OUT_TS = OUT_DIR / "content.ts"
OUT_HTML = OUT_DIR / "sections.html"
OUT_VARS = OUT_DIR / "palette.css"
OUT_SVG = PUBLIC_DIR / "motif.svg"


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def emit_palette_css() -> str:
    """Teal / coral / cream system — distinct from the plum portfolio."""
    return """/* Generated by build_content.py — impact palette */
:root {
  --ink: #0f2a27;
  --ink-soft: #1a3f3a;
  --muted: #4d6762;
  --teal-950: #071a18;
  --teal-900: #0f3d38;
  --teal-800: #16514a;
  --teal-700: #1d6a60;
  --teal-600: #2a8a7c;
  --teal-500: #3aa394;
  --teal-200: #b7e4db;
  --teal-100: #d9f2ed;
  --coral: #e8705f;
  --coral-deep: #d45a4a;
  --coral-soft: #f08a7a;
  --coral-100: #fdeeea;
  --cream: #faf7f3;
  --paper: #f4efe8;
  --sand: #ebe4da;
  --card: rgba(255, 252, 248, 0.72);
  --card-solid: #fffdfb;
  --line: rgba(15, 61, 56, 0.1);
  --glow-a: rgba(58, 163, 148, 0.32);
  --glow-b: rgba(232, 112, 95, 0.22);
  --glow-c: rgba(22, 81, 74, 0.18);
  --shadow: 0 28px 70px rgba(15, 61, 56, 0.12);
  --shadow-soft: 0 12px 36px rgba(15, 61, 56, 0.08);
  --radius: 22px;
  --radius-lg: 32px;
  --max: 1180px;
  --font-display: "Fraunces", "Iowan Old Style", Georgia, serif;
  --font-body: "Source Sans 3", system-ui, -apple-system, sans-serif;
  --header-bg: rgba(250, 247, 243, 0.78);
  --mesh-base: #f4efe8;
  --orb-1: rgba(58, 163, 148, 0.42);
  --orb-2: rgba(232, 112, 95, 0.32);
  --orb-3: rgba(26, 106, 96, 0.28);
  --glass: rgba(255, 252, 248, 0.55);
  --glass-border: rgba(255, 255, 255, 0.6);
  --accent-grad: linear-gradient(120deg, #2a8a7c, #3aa394 45%, #e8705f);
  --btn-grad: linear-gradient(135deg, #16514a, #2a8a7c 70%);
  --coral-grad: linear-gradient(135deg, #d45a4a, #e8705f 70%);
  --hero-grad: linear-gradient(155deg, #e8f6f3 0%, #faf7f3 42%, #fdeeea 100%);
  --connection-grad: linear-gradient(145deg, #071a18, #0f3d38 50%, #1d6a60);
  --stat-accent-bg: linear-gradient(160deg, rgba(232, 112, 95, 0.12), rgba(58, 163, 148, 0.1));
  --motif-opacity: 0.08;
  --on-dark: #faf7f3;
  --on-dark-muted: rgba(250, 247, 243, 0.78);
}

[data-theme="dark"] {
  --ink: #f0f7f5;
  --ink-soft: #d5ebe6;
  --muted: #9bb8b2;
  --teal-950: #e8f6f3;
  --teal-900: #b7e4db;
  --teal-800: #7dcec1;
  --teal-700: #3aa394;
  --teal-600: #5fbeb1;
  --teal-500: #7dcec1;
  --teal-200: #1d6a60;
  --teal-100: #0f3d38;
  --coral: #f08a7a;
  --coral-deep: #e8705f;
  --coral-soft: #f2a69a;
  --coral-100: #3a221e;
  --cream: #0a1614;
  --paper: #071a18;
  --sand: #0c2421;
  --card: rgba(15, 61, 56, 0.45);
  --card-solid: #0c2421;
  --line: rgba(240, 247, 245, 0.12);
  --glow-a: rgba(58, 163, 148, 0.2);
  --glow-b: rgba(232, 112, 95, 0.16);
  --glow-c: rgba(125, 206, 193, 0.1);
  --shadow: 0 28px 70px rgba(0, 0, 0, 0.45);
  --shadow-soft: 0 12px 36px rgba(0, 0, 0, 0.3);
  --header-bg: rgba(7, 26, 24, 0.82);
  --mesh-base: #071a18;
  --orb-1: rgba(58, 163, 148, 0.25);
  --orb-2: rgba(232, 112, 95, 0.18);
  --orb-3: rgba(125, 206, 193, 0.14);
  --glass: rgba(12, 36, 33, 0.55);
  --glass-border: rgba(240, 247, 245, 0.12);
  --accent-grad: linear-gradient(120deg, #5fbeb1, #7dcec1 45%, #f08a7a);
  --btn-grad: linear-gradient(135deg, #1d6a60, #2a8a7c 70%);
  --coral-grad: linear-gradient(135deg, #d45a4a, #e8705f 70%);
  --hero-grad: linear-gradient(155deg, #071a18 0%, #0c2421 45%, #1a1816 100%);
  --connection-grad: linear-gradient(145deg, #041210, #0a221f 50%, #134841);
  --stat-accent-bg: linear-gradient(160deg, rgba(232, 112, 95, 0.18), rgba(58, 163, 148, 0.14));
  --motif-opacity: 0.14;
  --on-dark: #faf7f3;
  --on-dark-muted: rgba(250, 247, 243, 0.78);
}
"""


def emit_motif_svg() -> str:
    """Procedural book-spine + leaf arcs — impact motif."""
    parts = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400" fill="none">',
        "<defs>",
        '<linearGradient id="g" x1="0" y1="0" x2="1" y2="1">',
        '<stop offset="0%" stop-color="#2a8a7c"/>',
        '<stop offset="55%" stop-color="#3aa394"/>',
        '<stop offset="100%" stop-color="#e8705f"/>',
        "</linearGradient>",
        "</defs>",
    ]
    # book spines
    for i, x in enumerate((120, 155, 190, 225)):
        h = 140 + (i % 3) * 28
        y = 200 - h / 2
        parts.append(
            f'<rect x="{x}" y="{y:.1f}" width="22" height="{h:.1f}" rx="3" '
            f'stroke="url(#g)" stroke-width="2" opacity="{0.35 + i * 0.08}"/>'
        )
    # leaf arcs
    cx, cy = 200.0, 200.0
    for i in range(10):
        angle = i * (math.pi / 5) + 0.15
        r = 95 + (i % 3) * 22
        x = cx + math.cos(angle) * r
        y = cy + math.sin(angle) * r
        mx = cx + math.cos(angle + 0.55) * (r * 0.55)
        my = cy + math.sin(angle + 0.55) * (r * 0.55)
        parts.append(
            f'<path d="M{cx:.1f},{cy:.1f} Q{mx:.1f},{my:.1f} {x:.1f},{y:.1f}" '
            f'stroke="url(#g)" stroke-width="{1.4 + (i % 3) * 0.35}" '
            f'stroke-linecap="round" opacity="{0.28 + (i % 4) * 0.08}"/>'
        )
    for i in range(7):
        a = i * (math.pi / 3.5) + 0.4
        r = 130 + (i % 2) * 25
        x = cx + math.cos(a) * r
        y = cy + math.sin(a) * r
        parts.append(
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{3.5 + (i % 3)}" '
            f'fill="url(#g)" opacity="0.4"/>'
        )
    parts.append(f'<circle cx="{cx}" cy="{cy}" r="7" fill="url(#g)" opacity="0.65"/>')
    parts.append("</svg>")
    return "\n".join(parts)


ICONS = {
    "libraries": """<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><rect x="8" y="14" width="18" height="36" rx="2" stroke="currentColor" stroke-width="2.5"/><rect x="26" y="10" width="18" height="40" rx="2" stroke="currentColor" stroke-width="2.5"/><rect x="44" y="16" width="12" height="34" rx="2" stroke="currentColor" stroke-width="2.5"/><path d="M17 22h4M17 28h4M35 18h4M35 24h4M50 22h4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>""",
    "donations": """<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><path d="M32 12v8M20 24h24" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/><rect x="14" y="28" width="36" height="24" rx="3" stroke="currentColor" stroke-width="2.5"/><path d="M14 36h36M26 28v24M38 28v24" stroke="currentColor" stroke-width="2" opacity="0.7"/><circle cx="48" cy="20" r="8" stroke="currentColor" stroke-width="2.5"/><path d="M48 16v8M44 20h8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>""",
    "fundraising": """<svg viewBox="0 0 64 64" fill="none" aria-hidden="true"><circle cx="32" cy="32" r="22" stroke="currentColor" stroke-width="2.5"/><path d="M32 18v28M24 24c0-4 3.5-6 8-6s8 2 8 6-3.5 5-8 5-8 2-8 6 3.5 6 8 6 8-2 8-6" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>""",
}


def build_sections(data: dict) -> str:
    p = data["person"]
    hero = data["hero"]
    about = data["about"]
    impact = data["impact"]
    contrib = data["contributions"]
    campaigns = data["campaigns"]
    orgs = data["organizations"]
    connection = data["connection"]
    evidence = data["evidence"]
    contact = data["contact"]
    honesty = data["honesty"]

    tags = "".join(f"<li>{esc(t)}</li>" for t in hero["tags"])

    facts = "\n".join(
        f'<div class="fact-card glass reveal" data-tilt style="--i:{i}">'
        f'<span class="fact-label">{esc(f["label"])}</span>'
        f"<strong>{esc(f['value'])}</strong></div>"
        for i, f in enumerate(about["facts"])
    )
    about_ps = "\n".join(f"<p>{esc(para)}</p>" for para in about["paragraphs"])

    # Impact stat groups
    impact_blocks = []
    for gi, group in enumerate(impact["groups"]):
        cards = []
        for i, s in enumerate(group["stats"]):
            accent = " accent" if s.get("accent") else ""
            cards.append(
                f'''<article class="stat-card glass reveal{accent}" data-tilt style="--i:{i}">
  <p class="stat-number">{esc(s["value"])}</p>
  <p class="stat-label">{esc(s["label"])}</p>
  <p class="stat-source">{esc(s["source"])}</p>
</article>'''
            )
        impact_blocks.append(
            f'''<div class="stats-org reveal" style="--i:{gi}">
  <h3 class="stats-org-name">{esc(group["org"])} <span>{esc(group["aka"])}</span></h3>
  <div class="stat-grid">{"".join(cards)}</div>
</div>'''
        )

    # Contribution cards
    contrib_cards = []
    for i, c in enumerate(contrib["cards"]):
        icon = ICONS.get(c.get("icon", ""), ICONS["libraries"])
        contrib_cards.append(
            f'''<article class="contrib-card glass reveal" data-tilt style="--i:{i}">
  <div class="card-icon" aria-hidden="true">{icon}</div>
  <h3>{esc(c["title"])}</h3>
  <p>{esc(c["body"])}</p>
  <p class="card-note">{esc(c["note"])}</p>
</article>'''
        )

    # Timeline
    timeline = []
    for i, item in enumerate(campaigns["items"]):
        accent = " accent" if item.get("accent") else ""
        timeline.append(
            f'''<li class="timeline-item reveal{accent}" style="--i:{i}">
  <div class="timeline-marker" aria-hidden="true"></div>
  <div class="timeline-body glass">
    <p class="timeline-when">{esc(item["when"])}</p>
    <h3>{esc(item["title"])}</h3>
    <p>{esc(item["body"])}</p>
    <p class="timeline-source">Source: {esc(item["source"])}</p>
  </div>
</li>'''
        )

    # Org panels
    org_panels = []
    for i, panel in enumerate(orgs["panels"]):
        stats = "".join(
            f"<li>{esc(s)}</li>" for s in panel["stats"]
        )
        org_panels.append(
            f'''<article class="org-panel glass reveal" data-tilt style="--i:{i}">
  <h3>{esc(panel["name"])}</h3>
  <p class="org-aka">{esc(panel["aka"])}</p>
  <p>{esc(panel["body"])}</p>
  <ul class="org-stats">{stats}</ul>
  <p class="org-note">{esc(panel["note"])}</p>
  <a class="org-link magnetic" href="{esc(panel["url"])}" target="_blank" rel="noopener noreferrer">
    <span>{esc(panel["urlLabel"])} →</span>
  </a>
</article>'''
        )

    conn_ps = "\n".join(f"<p>{esc(para)}</p>" for para in connection["paragraphs"])

    evidence_slots = []
    for i, slot in enumerate(evidence["slots"]):
        hl = " highlight" if slot.get("highlight") else ""
        evidence_slots.append(
            f'''<div class="evidence-slot glass reveal{hl}" style="--i:{i}">
  <h3>{esc(slot["title"])}</h3>
  <p>{esc(slot["status"])}</p>
</div>'''
        )

    contact_links = []
    for i, link in enumerate(contact["links"]):
        external = ' target="_blank" rel="noopener noreferrer"' if link["href"].startswith("http") else ""
        contact_links.append(
            f'''<a class="contact-card glass magnetic reveal" href="{esc(link["href"])}"{external} style="--i:{i}">
  <span class="contact-label">{esc(link["label"])}</span>
  <span class="contact-value">{esc(link["value"])}</span>
</a>'''
        )

    first = p["name"].split()[0]
    last = p["name"].split()[-1]

    return f'''<!-- Generated by build_content.py — do not edit by hand -->
<section class="hero" id="home" aria-labelledby="hero-title">
  <div class="hero-bg" aria-hidden="true">
    <div class="mesh"></div>
    <div class="orb orb-a"></div>
    <div class="orb orb-b"></div>
    <div class="orb orb-c"></div>
    <div class="motif-layer"></div>
    <div class="grid-lines"></div>
  </div>
  <div class="container hero-layout">
    <div class="hero-copy reveal">
      <p class="eyebrow"><span class="pulse" aria-hidden="true"></span>{esc(hero["eyebrow"])}</p>
      <p class="hero-role">{esc(p["volunteerRole"])}</p>
      <h1 id="hero-title">
        <span class="name-line">{esc(hero["title"])}</span>
        <span class="name-accent">{esc(first)} {esc(last)}</span>
      </h1>
      <p class="hero-tagline">{esc(p["tagline"])}</p>
      <p class="hero-lead">{esc(hero["lead"])}</p>
      <div class="hero-cta">
        <a class="btn btn-solid magnetic" href="{esc(hero["ctaPrimary"]["href"])}"><span>{esc(hero["ctaPrimary"]["label"])}</span></a>
        <a class="btn btn-ghost magnetic" href="{esc(hero["ctaSecondary"]["href"])}"><span>{esc(hero["ctaSecondary"]["label"])}</span></a>
      </div>
      <ul class="hero-tags" aria-label="Focus areas">{tags}</ul>
    </div>
    <aside class="hero-aside reveal" style="--i:1" aria-label="Snapshot">
      <div class="aside-card glass">
        <p class="aside-kicker">At a glance</p>
        <dl>
          <div><dt>Role</dt><dd>{esc(p["role"])} · {esc(p["company"])}</dd></div>
          <div><dt>Volunteer</dt><dd>Libraries · Drives · Fundraising</dd></div>
          <div><dt>Partners</dt><dd>Prashraya · Hamari Pahchan</dd></div>
        </dl>
        <p class="aside-honesty">{esc(honesty["banner"])}</p>
      </div>
    </aside>
  </div>
  <a class="scroll-cue magnetic" href="#impact" aria-label="Scroll to impact"><span>↓</span></a>
</section>

<section class="section impact" id="impact" aria-labelledby="impact-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(impact["tag"])}</p>
      <h2 id="impact-title">{esc(impact["title"])}</h2>
      <p class="section-intro">{esc(impact["intro"])}</p>
    </div>
    <p class="honesty-banner glass reveal">{esc(honesty["banner"])}</p>
    {"".join(impact_blocks)}
  </div>
</section>

<section class="section about" id="about" aria-labelledby="about-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(about["tag"])}</p>
      <h2 id="about-title">{esc(about["title"])}</h2>
    </div>
    <div class="about-grid">
      <div class="about-copy reveal">{about_ps}
        <div class="about-links">
          <a class="magnetic" href="{esc(p["linkedin"])}" target="_blank" rel="noopener noreferrer">LinkedIn</a>
          <a class="magnetic" href="{esc(p["portfolio"])}" target="_blank" rel="noopener noreferrer">Portfolio</a>
          <a class="magnetic" href="{esc(p["github"])}" target="_blank" rel="noopener noreferrer">GitHub</a>
        </div>
      </div>
      <div class="about-facts">{facts}</div>
    </div>
  </div>
</section>

<section class="section contributions" id="contributions" aria-labelledby="contrib-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(contrib["tag"])}</p>
      <h2 id="contrib-title">{esc(contrib["title"])}</h2>
      <p class="section-intro">{esc(contrib["intro"])}</p>
    </div>
    <div class="card-grid">{"".join(contrib_cards)}</div>
  </div>
</section>

<section class="section campaigns" id="campaigns" aria-labelledby="campaigns-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(campaigns["tag"])}</p>
      <h2 id="campaigns-title">{esc(campaigns["title"])}</h2>
      <p class="section-intro">{esc(campaigns["intro"])}</p>
    </div>
    <ol class="timeline">
      <div class="timeline-rail" aria-hidden="true"></div>
      {"".join(timeline)}
    </ol>
  </div>
</section>

<section class="section orgs" id="organizations" aria-labelledby="orgs-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(orgs["tag"])}</p>
      <h2 id="orgs-title">{esc(orgs["title"])}</h2>
      <p class="section-intro">{esc(orgs["intro"])}</p>
    </div>
    <div class="org-panels">{"".join(org_panels)}</div>
  </div>
</section>

<section class="section connection" id="connection" aria-labelledby="connect-title">
  <div class="container narrow">
    <div class="connection-banner reveal">
      <p class="section-tag light">{esc(connection["tag"])}</p>
      <h2 id="connect-title">{esc(connection["title"])}</h2>
      <div class="connection-visual" aria-hidden="true">
        <span>Books</span><span class="dot"></span><span>Support</span><span class="dot"></span><span>Access</span>
      </div>
      {conn_ps}
    </div>
  </div>
</section>

<section class="section evidence" id="evidence" aria-labelledby="evidence-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(evidence["tag"])}</p>
      <h2 id="evidence-title">{esc(evidence["title"])}</h2>
      <p class="section-intro">{esc(evidence["intro"])}</p>
    </div>
    <div class="evidence-strip">{"".join(evidence_slots)}</div>
  </div>
</section>

<section class="section contact" id="contact" aria-labelledby="contact-title">
  <div class="container">
    <div class="section-head reveal">
      <p class="section-tag">{esc(contact["tag"])}</p>
      <h2 id="contact-title">{esc(contact["title"])}</h2>
      <p class="section-intro">{esc(contact["blurb"])}</p>
    </div>
    <div class="contact-grid">{"".join(contact_links)}</div>
  </div>
</section>
'''


def to_ts_module(data: dict) -> str:
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    return (
        "/* Generated by build_content.py — do not edit by hand */\n"
        f"export const content = {payload} as const;\n"
        "export type SiteContent = typeof content;\n"
    )


def main() -> None:
    data = json.loads(CONTENT_PATH.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)

    OUT_TS.write_text(to_ts_module(data), encoding="utf-8")
    OUT_HTML.write_text(build_sections(data), encoding="utf-8")
    OUT_VARS.write_text(emit_palette_css(), encoding="utf-8")
    OUT_SVG.write_text(emit_motif_svg(), encoding="utf-8")
    (OUT_DIR / "content.snapshot.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Wrote {OUT_TS.relative_to(ROOT)}")
    print(f"Wrote {OUT_HTML.relative_to(ROOT)}")
    print(f"Wrote {OUT_VARS.relative_to(ROOT)}")
    print(f"Wrote {OUT_SVG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
